### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vityafx** [vityafx/cargo-cook#1]
This project is in a very early development stage.

- [ ] Remove `cargo` warnings which say about unhandled `Cargo.toml` attribute.
- [ ] Include dependencies somehow (discussable)
- [ ] Provide hash algorithms for `sha1sum`, `sha224sum`, `sha256sum`, `sha384sum` and `sha512sum`
- [ ] Provide different containers support for `zip`, `7z`, `rar`, `tar.gz`, `tar.bzip2`, `lzma`, and many more as it is possible.
- [ ] Implement ingredients handling.
- [ ] Conditional compilation based on containerers, hashes and other stuff which can be conditionally-compiled and used as feature.
- [ ] Propose to integrate it into a real cargo subcommand.
- [ ] Add a normal way of determing target directory. Now it is explicitly specified in the config file (BAD).

Based on above the fields which are not properly handled are:

- `cook.target_name`: Must rename target file before packaging into an archive.
- `cook.hashes`: Simply not handled at all.
- `cook.containers`: Simply not handled at all.
- `include_dependencies`: Must include dependencies (I don't know is it possible or not yet).
- `cook.ingredient`: Must copy files specified by `source` attribute (must be a regular expression) to `destination` folder.
